### ISSUE TITLE
Eclipse.cpp&c.Error127

### ISSUE THREAD

**Issue by jkhdr5426** [bhengine/bluehydra-#1]

**Comment by megadiamond9257** [comment]
The current builder of the project may not be compatible with the current toolchain. Usually, if you are using a Cross GCC toolchain (Project/Properties/"C++/C Build"/Tool Chain Editor), you would use the CDT Internal Builder as your current builder (Project/Properties/"C++/C Build"/Tool Chain Editor).

**Comment by jkhdr5426** [comment]
The current builder of the project may not be compatible with the current toolchain. Usually, if you are using a Cross GCC toolchain (Project/Properties/"C++/C Build"/Tool Chain Editor), you would use the CDT Internal Builder as your current builder (Project/Properties/"C++/C Build"/Tool Chain Editor).
