### ISSUE TITLE
Eclipse.cpp&c.Error(Unresolved Inclusion <(somelib)>; root: invalid preprocessor directive)

### ISSUE THREAD

**Issue by jkhdr5426** [bhengine/bluehydra-#2]

**Comment by megadiamond9257** [comment]
There is no default library files for the project, so you would use the XCode C++ framework libraries (you need to install XCode, or any other complete C++ framework library collection) to solve it. To do this, navigate to Project/Properties/"C/C++ General"/Preprocessor Include Paths, Macros etc./Providers and select "CDT Cross GCC Built-in Compiler Settings" with "Use global provider shared between projects" underneath.

**Comment by jkhdr5426** [comment]
There is no default library files for the project, so you would use the XCode C++ framework libraries (you need to install XCode, or any other complete C++ framework library collection) to solve it. To do this, navigate to Project/Properties/"C/C++ General"/Preprocessor Include Paths, Macros etc./Providers and select "CDT Cross GCC Built-in Compiler Settings" with "Use global provider shared between projects" underneath.
